---
version: '3.5'
services:
  revproxy:
    build:
      context: ./revproxy
    depends_on:
      - http-service
    ports:
      - 8443:443
    networks:
      - revproxy
  http-service:
    image: nginx
    volumes:
      - ./http-service/index.html:/www/data/index.html
      - ./http-service/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - revproxy
networks:
  revproxy: {}
